#!/bin/bash

#SBATCH --partition=short
#SBATCH --nodes=1
#SBATCH --ntasks 1
#SBATCH --cpus-per-task 56
#SBATCH --time=24:00:00
#SBATCH --mem=178G
#SBATCH --export=ALL
#SBATCH --constraint=cascadelake

module load R && module load nodejs && module load anaconda3 ;
conda init bash
conda activate farbod
conda activate farbod
cd /work/postresearch/Shared/Projects/Farbod/CaseMix ;
Rscript /work/postresearch/Shared/Projects/Farbod/CaseMix/calculations_sbatch.r
